export { default as Hero } from './Hero';
export { default as HeroVariant1 } from './HeroVariant1';
export { default as HeroVariant2 } from './HeroVariant2';
export { default as HeroVariant3 } from './HeroVariant3';
export { default as HeroVariant4 } from './HeroVariant4';
export { default as About } from './About';
export { default as LatestBlog } from './LatestBlog';
export { default as Contact } from './Contact';
export { default as HomeGallery } from './HomeGallery';
